# Autoshift Generator script
# Generates Kanata autoshift configuration files. Based on this discussion: https://github.com/jtroo/kanata/discussions/470
# The number of milliseconds to wait for a key to be held down before sending the key is the first number, the number of milliseconds 
# after the tap-hold-press-timeout may need to be adjusted.
 
print ('(defalias')
print (";; Autoshift configuration generated by autoshift-generator/generate-autoshift-config.py")
chars = "abcdefghijklmnopqrstuvwxyz1234567890`-=[]\\;',./"
for char in chars:
  print ('{0} (tap-hold-press-timeout $tt $ht {0} {0} (macro S-{0}))'.format(char))
print (')')